services:
  zk:
    image: ghcr.io/matter-labs/zk-environment:latest2.0-lightweight-nightly
    extends:
      file: docker-compose.yml
      service: zk

  postgres:
    extends:
      file: docker-compose.yml
      service: postgres

  l1:
    extends:
      file: docker-compose.yml
      service: l1

volumes:
  postgres-data:
  l1_data: